;/;# 47 Reverse a String


In [10]:
def reverseString(self, s: List[str]) -> None:
    for i in range(len(s)):

        s[i],s[len(s)-1-i]=s[len(s)-1-i],s[i]
        if i>=len(s)//2-1:
            break
    print(s)
    return s

tijihba

# 48 Check whether a String is Palindrome or not


In [41]:
a="abcacba"
flag=1
for i in range(len(a)//2):
    if (a[i]!=a[len(a)-i-1]):       #palindrome nahi
        flag=0
print(flag)

1


# Check whether a String is Palindrome or not after removing at least one element


In [ ]:
def validPalindrome(self, s: str) -> bool:
    print('--------')
    if s[:]==s[::-1]:
        return True
        #pass
    flag=1
    n=len(s)
    for i in range(len(s)-1):
        if s[i]==s[n-i-1]:
            continue
        else:
            a=s[i+1:n-i]
            print(a,a[::-1])
            if a==a[::-1]:
                return True
            a=s[i:n-i-1]
            print(a,a[::-1])
            if a==a[::-1]:
                return True
            return False

    return False

# 49	Find Duplicate characters in a string


In [72]:
from collections import Counter      
def printDups(st):
    x=Counter(st)
    #print(x)
    for i in x:
        #print(x[i])
        if x[i]>=2:
            print(i,x[i])
    
    return st
string = "test string"
print (printDups(string))

t 3
s 2
test string


# 51	Write a Code to check whether one string is a rotation of another


In [8]:
a='abhijit'
b='itabhij'
for i in range(len(a)):
    a=a[1:]+a[0]
    if a==b:
        print(i)
    print(a)

bhijita
hijitab
ijitabh
jitabhi
4
itabhij
tabhiji
abhijit


In [13]:
a='abhijit'
b='jitabhi'
a=a+a
a
if b in a:
    print('rotation')

rotation


# 52	Write a Program to check whether a string is a valid shuffle of two strings or not


In [46]:
A = "AB"
B = "CD"
C = "ACBD"

if len(A)+len(B)==len(C):
    print('return 0')
    #return 0
a=sorted(A+B)
a=''.join(a)
print(a)

c=sorted(C)
c=''.join(c)
print(c)
if a==c:
    print('Yes, it is')


return 0
ABCD
ABCD
Yes, it is


# 53	Count and Say problem

In [80]:
'''
In such problems always start searching from ix=1 and compare a[i-1] to curr
handle last index
'''
a='12113334455'
b=[]
cur=a[0]
#print(a[0])
#lst=0
cnt=0

for i in range(len(a)):
    if i==(len(a)-1):
        #print(cnt,cur,a[i-1],a[i])
        if cur==a[i-1]:
            cnt=cnt+1
            
             
        break
    if cur==a[i+1]:
        cnt=cnt+1      
        #print(cnt,cur,a[i+1])
        cur=a[i+1]
    if cur!=a[i+1]:
        cnt=cnt+1       
        #print(cnt,cur,a[i+1],'-')
        print(cnt,cur,sep='',end='')
        cur=a[i+1]
        #lst=cnt
        cnt=0

1112213324

# 54	Write a program to find the longest Palindrome in a string.[ Longest palindromic Substring]


In [284]:
a='abhijit'

print(a[2:4],a[4-1:2-1:-1])
print(j-i+1)


hi ih
2


In [104]:
S='vnrtysfrzrmzlygfv'
lle=1
re=1
ressul=''
for i in range(len(S)):
    for j in range(i+1,len(S)+1):
        #print(i,j)
        #print(S[i:j],end='')
    
        print(S[i:j],'\t\t\t\t',S[j-1:i-1:-1])
        if S[i:j]==S[j-1:i-1:-1]:
            print('Gaot')#f'{s:>5}
            re=j-1+1
            
            
            if len(S[i:j])>len(ressul):
                lle=S[i:j]
                ressul=S[i:j]
                print(re, ressul)
if len(ressul)==1:
    print( S[0])
print('ressul',ressul)

v 				 
vn 				 
vnr 				 
vnrt 				 
vnrty 				 
vnrtys 				 
vnrtysf 				 
vnrtysfr 				 
vnrtysfrz 				 
vnrtysfrzr 				 
vnrtysfrzrm 				 
vnrtysfrzrmz 				 
vnrtysfrzrmzl 				 
vnrtysfrzrmzly 				 
vnrtysfrzrmzlyg 				 
vnrtysfrzrmzlygf 				 
vnrtysfrzrmzlygfv 				 
n 				 n
Gaot
2 n
nr 				 rn
nrt 				 trn
nrty 				 ytrn
nrtys 				 sytrn
nrtysf 				 fsytrn
nrtysfr 				 rfsytrn
nrtysfrz 				 zrfsytrn
nrtysfrzr 				 rzrfsytrn
nrtysfrzrm 				 mrzrfsytrn
nrtysfrzrmz 				 zmrzrfsytrn
nrtysfrzrmzl 				 lzmrzrfsytrn
nrtysfrzrmzly 				 ylzmrzrfsytrn
nrtysfrzrmzlyg 				 gylzmrzrfsytrn
nrtysfrzrmzlygf 				 fgylzmrzrfsytrn
nrtysfrzrmzlygfv 				 vfgylzmrzrfsytrn
r 				 r
Gaot
rt 				 tr
rty 				 ytr
rtys 				 sytr
rtysf 				 fsytr
rtysfr 				 rfsytr
rtysfrz 				 zrfsytr
rtysfrzr 				 rzrfsytr
rtysfrzrm 				 mrzrfsytr
rtysfrzrmz 				 zmrzrfsytr
rtysfrzrmzl 				 lzmrzrfsytr
rtysfrzrmzly 				 ylzmrzrfsytr
rtysfrzrmzlyg 				 gylzmrzrfsytr
rtysfrzrmzlygf 				 fgylzmrzrfsytr
rtysfrzrmzlygfv 				 v

In [169]:
def longestPalin( s):
    left=0
    right=0
    if len(s)<=2:
        if s[:]==s[::-1]:
            return s
        return s[0]

    n=len(s)
    c=1
    m=[[0 for i in range(len(s))] for i in range(len(s))]
    for i in range(len(m)-1):
        m[i][i]=1
        if s[i]==s[i+1]:
            m[i][i+1]=1
            if c>0:
                left=i
                right=i+1
                c-=1
            
    m[len(s)-1][len(s)-1]=1
    print(m)

    for i in range(n,-1,-1):
        for j in range(i+2,n):
            
                print(i,j)
                if s[i]==s[j] and m[i+1][j-1]==1:
                    m[i][j]=1
                    print(i,j,'ij')
                    if j-i>=right-left:
                        right=j
                        left=i
    
    print(m)
    print(right,left,'ijij')
    print(s[left:right+1])
longestPalin('aaaabbaa')

[[1, 1, 0, 0, 0, 0, 0, 0], [0, 1, 1, 0, 0, 0, 0, 0], [0, 0, 1, 1, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 1, 1, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 1, 1], [0, 0, 0, 0, 0, 0, 0, 1]]
5 7
4 6
4 7
3 5
3 6
3 6 ij
3 7
2 4
2 5
2 6
2 7
2 7 ij
1 3
1 3 ij
1 4
1 5
1 6
1 7
0 2
0 2 ij
0 3
0 3 ij
0 4
0 5
0 6
0 7
[[1, 1, 1, 1, 0, 0, 0, 0], [0, 1, 1, 1, 0, 0, 0, 0], [0, 0, 1, 1, 0, 0, 0, 1], [0, 0, 0, 1, 0, 0, 1, 0], [0, 0, 0, 0, 1, 1, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 1, 1], [0, 0, 0, 0, 0, 0, 0, 1]]
7 2 ijij
aabbaa


In [133]:
'''crazy idea.. no need to traverse diagonal'''
n=8
a=[[0]*n for i in range(n)]
cnt=0
for i in range(n-2,-1,-1):
    for j in range(i+1,n):
        cnt+=1
        a[i][j]=cnt
a

[[0, 22, 23, 24, 25, 26, 27, 28],
 [0, 0, 16, 17, 18, 19, 20, 21],
 [0, 0, 0, 11, 12, 13, 14, 15],
 [0, 0, 0, 0, 7, 8, 9, 10],
 [0, 0, 0, 0, 0, 4, 5, 6],
 [0, 0, 0, 0, 0, 0, 2, 3],
 [0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0]]

#  Substring of a string.


In [103]:
'''MY substring'''
from itertools import combinations_with_replacement
str='abc'
for i,j in combinations_with_replacement(range(len(str)),2):
    #print(i,j)
    print(str[i:j+1])
    

a
ab
abc
b
bc
c


In [91]:
from itertools import combinations
str='abc'
for i in combinations('abc',2):
    print(i)

('a', 'b')
('a', 'c')
('b', 'c')


In [66]:
from itertools import combinations_with_replacement

s = 'MISSISSIPPI'
lst = []

for i,j in combinations_with_replacement(range(len(s)), 2):
    if s[i:(j+1)] not in lst:
        lst.append(s[i:(j+1)]) # save new combination into list
        print(lst[-1]) # print new combination

M
MI
MIS
MISS
MISSI
MISSIS
MISSISS
MISSISSI
MISSISSIP
MISSISSIPP
MISSISSIPPI
I
IS
ISS
ISSI
ISSIS
ISSISS
ISSISSI
ISSISSIP
ISSISSIPP
ISSISSIPPI
S
SS
SSI
SSIS
SSISS
SSISSI
SSISSIP
SSISSIPP
SSISSIPPI
SI
SIS
SISS
SISSI
SISSIP
SISSIPP
SISSIPPI
ISSIP
ISSIPP
ISSIPPI
SSIP
SSIPP
SSIPPI
SIP
SIPP
SIPPI
IP
IPP
IPPI
P
PP
PPI
PI


In [84]:
from itertools import combinations_with_replacement
for i,j,k in combinations_with_replacement(range(5), 3):
    print(i,j,k)

0 0 0
0 0 1
0 0 2
0 0 3
0 0 4
0 1 1
0 1 2
0 1 3
0 1 4
0 2 2
0 2 3
0 2 4
0 3 3
0 3 4
0 4 4
1 1 1
1 1 2
1 1 3
1 1 4
1 2 2
1 2 3
1 2 4
1 3 3
1 3 4
1 4 4
2 2 2
2 2 3
2 2 4
2 3 3
2 3 4
2 4 4
3 3 3
3 3 4
3 4 4
4 4 4


# 55	Find Longest Recurring Subsequence in String


In [62]:
import numpy as np
str='axxxy'
str1=str
nn=len(str)
mm=[[0 for k in range(nn+1)] for l in range(nn+1)]  #mm=np.zeros([x+1,y+1])
mm

for i in range(1,len(mm)):
    for j in range(1,len(mm)):
        if str[i-1]==str1[j-1] and i!=j:
            mm[i][j]=1+mm[i-1][j-1]
    
        else:
            mm[i][j]=max(mm[i-1][j],mm[i][j-1])

mm

[[0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 1, 1],
 [0, 0, 1, 1, 2, 2],
 [0, 0, 1, 2, 2, 2],
 [0, 0, 1, 2, 2, 2]]

# 56	Print all Subsequences of a string.


In [171]:
'''MY N^2'''
from itertools import combinations
for i in range(1,len('abc')+1):
    for j in combinations('abc',i):
        print(i,list(j))

1 ['a']
1 ['b']
1 ['c']
2 ['a', 'b']
2 ['a', 'c']
2 ['b', 'c']
3 ['a', 'b', 'c']


In [178]:
'''MY recurssive Programing'''
str='abc'
def ss(str,output):
    if len(str)==0:
        print(output)
        return
    
    ss(str[1:],output+str[0])
    
    ss(str[1:],output)
    
output=''  
ss(str,output)   

abc
ab
ac
a
bc
b
c



In [109]:
'''N^2'''
from itertools import combinations
s='Hello'
def all_subsequences(s):
    out = set()
    for r in range(1, len(s) + 1):
        for c in combinations(s, r):
            out.add(''.join(c))
    return sorted(out)
all_subsequences('abc')

['a', 'ab', 'abc', 'ac', 'b', 'bc', 'c']

In [214]:
'''2N'''
import itertools

def Sub_Sequences(STR):
	combs = []
	for l in range(1, len(STR)+1):
		combs.append(list(itertools.combinations(STR, l)))
		print(combs)
	for c in combs:
		for t in c:
			print (''.join(t), end =' ')

# Testing with driver code
Sub_Sequences('abc')

[[('a',), ('b',), ('c',)]]
[[('a',), ('b',), ('c',)], [('a', 'b'), ('a', 'c'), ('b', 'c')]]
[[('a',), ('b',), ('c',)], [('a', 'b'), ('a', 'c'), ('b', 'c')], [('a', 'b', 'c')]]
a b c ab ac bc abc 

In [175]:
aa=[]
aa.append(list(itertools.combinations('1122',2)))

print(aa)

[[('1', '1'), ('1', '2'), ('1', '2'), ('1', '2'), ('1', '2'), ('2', '2')]]


# 57	Print all the permutations of the given string


In [ ]:
def find_permutation(self, s):
        # Code here
        n=len(s)
        re=[]
        import itertools
        for i in itertools.permutations(s,n):
            re.append(''.join(i))
        #print(re)
        return sorted(re)

In [262]:
'''MY'''
import itertools
for i,j,k in itertools.permutations('ABC',3):
    print(i,j,k,sep='',end=' ')

ABC ACB BAC BCA CAB CBA 

In [236]:
nums = list("ABC")
permutations = list(itertools.permutations(nums))
print(permutations)
# Output: ['ABC', 'ACB', 'BAC', 'BCA', 'CAB', 'CBA']
print([''.join(permutation) for permutation in permutations])

[('A', 'B', 'C'), ('A', 'C', 'B'), ('B', 'A', 'C'), ('B', 'C', 'A'), ('C', 'A', 'B'), ('C', 'B', 'A')]
['ABC', 'ACB', 'BAC', 'BCA', 'CAB', 'CBA']


In [261]:
import itertools
S='ABC'
y=''
x=[]
x.append(list(itertools.permutations(S,len(S))))
x
for i in range(len(k)):
    for k in x:
        y=''.join(k[i])
        print(y ,end=' ')


ABC ACB BAC BCA CAB CBA 

In [284]:
'''MY Dynamic'''
import string
def permu(a,l,r):
    #print(a,l,r)
    
    if l==r:
        print(toString(a))
    else:
        for i in range(l,r+1):
            a[l],a[i]=a[i],a[l]
            permu(a,l+1,r)
            a[l],a[i]=a[i],a[l]
a=list('abc')
#print(a)
permu(a,0,len(a)-1)
    

abc
acb
bac
bca
cba
cab


In [226]:
def perms(in_str, prefix=""):
    if not len(in_str) :
        print(prefix)
    else:        
        for i in range(0, len(in_str)):
            perms(in_str[:i] + in_str[i + 1:], prefix + in_str[i])

perms('ASD')

ASD
ADS
SAD
SDA
DAS
DSA


In [228]:
def get_permutations(string):

    # base case
    if len(string) <= 1:
        return set([string])

    all_chars_except_last = string[:-1]
    last_char = string[-1]

    # recursive call: get all possible permutations for all chars except last
    permutations_of_all_chars_except_last = get_permutations(all_chars_except_last)

    # put the last char in all possible positions for each of the above permutations
    permutations = set()
    for permutation_of_all_chars_except_last in permutations_of_all_chars_except_last:
        for position in range(len(all_chars_except_last) + 1):
            permutation = permutation_of_all_chars_except_last[:position] + last_char + permutation_of_all_chars_except_last[position:]
            permutations.add(permutation)

    return permutations
get_permutations('ABC')

{'ABC', 'ACB', 'BAC', 'BCA', 'CAB', 'CBA'}

In [232]:
from typing import Iterator

def permutations(string: str, prefix: str = '') -> Iterator[str]:
    if len(string) == 0:
        yield prefix
    for i, character in enumerate(string):
        yield from permutations(string[:i] + string[i + 1:], prefix + character)
        
for p in permutations('abc'):
    print(p)

abc
acb
bac
bca
cab
cba


In [233]:
def permutations(s):
    if len(s) == 1 or len(s) == 0:
        return s
    _permutations = []
    for permutation in permutations(s[1:]):
        for i in range(len(permutation) + 1):
            _permutations.append(permutation[:i] + s[0] + permutation[i:])
    return _permutations


def main(s):
    print(permutations(s))


if __name__ == '__main__':
    main('abc')

['abc', 'bac', 'bca', 'acb', 'cab', 'cba']


In [234]:
https://www.techiedelight.com/find-all-permutations-string-python/

SyntaxError: invalid syntax (<ipython-input-234-9dcf44c210c8>, line 1)

# 58	Split the Binary string into two substring with equal 0’s and 1’s


In [290]:
str = '0100110101' 
cnt=0
zer=0
on=0
for x in str:
    if x=='0':
        zer+=1
    if x=='1':
        on+=1
    if zer==on:
        cnt+=1
        zer=0
        on=0
if cnt==0:
    print(-1)
else:
    print(cnt)

4


# 59	Word Wrap Problem [VERY IMP].


In [305]:
import itertools
list(itertools.permutations([1, 2, 3]))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]

In [331]:
from itertools import combinations
y=[]
def solveWordWrap(nums,k):
    x= y.extend(list(itertools.permutations(nums)))
    #print(x,end='')
    print(y)
    
    

nums=[3,2,2,5]
k=6
solveWordWrap(nums,k)

[(3, 2, 2, 5), (3, 2, 5, 2), (3, 2, 2, 5), (3, 2, 5, 2), (3, 5, 2, 2), (3, 5, 2, 2), (2, 3, 2, 5), (2, 3, 5, 2), (2, 2, 3, 5), (2, 2, 5, 3), (2, 5, 3, 2), (2, 5, 2, 3), (2, 3, 2, 5), (2, 3, 5, 2), (2, 2, 3, 5), (2, 2, 5, 3), (2, 5, 3, 2), (2, 5, 2, 3), (5, 3, 2, 2), (5, 3, 2, 2), (5, 2, 3, 2), (5, 2, 2, 3), (5, 2, 3, 2), (5, 2, 2, 3)]


# 60	EDIT Distance [Very Imp]


In [1]:
class Solution:
    def editDistance(self, s, t):

        import numpy as np
        a=np.zeros([len(s)+1,len(t)+1])
        #print(a)
        for i in range(len(s)+1):
            for j in range(len(t)+1):
                if j==0:
                    a[i][j]=i
                if i==0:
                    a[i][j]=j
                    
        for i in range(1,len(s)+1):
            for j in range(1,len(t)+1):                
                if s[i-1]==t[j-1]:
                        a[i][j]=a[i-1][j-1]  # +1
                else:
                    a[i][j]=1+min(a[i-1][j-1],a[i][j-1],a[i-1][j])
                                    #replace   #inset    #remove
        print(a)
        return int(a[len(s)][len(t)])

if __name__ == '__main__':
		s, t = 'geek','geeak'
		ob = Solution();
		ans = ob.editDistance(s, t)
		print(ans)

[[0. 1. 2. 3. 4. 5.]
 [1. 0. 1. 2. 3. 4.]
 [2. 1. 0. 1. 2. 3.]
 [3. 2. 1. 0. 1. 2.]
 [4. 3. 2. 1. 1. 1.]]
1


In [2]:
a=[1, 2, 3, 6, 5, 4]
n=len(a)
from itertools import permutations
for i in permutations(a,len(a)):
    print(list(i))
    if list(i)==a:
        print('break')

[1, 2, 3, 6, 5, 4]
break
[1, 2, 3, 6, 4, 5]
[1, 2, 3, 5, 6, 4]
[1, 2, 3, 5, 4, 6]
[1, 2, 3, 4, 6, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 6, 3, 5, 4]
[1, 2, 6, 3, 4, 5]
[1, 2, 6, 5, 3, 4]
[1, 2, 6, 5, 4, 3]
[1, 2, 6, 4, 3, 5]
[1, 2, 6, 4, 5, 3]
[1, 2, 5, 3, 6, 4]
[1, 2, 5, 3, 4, 6]
[1, 2, 5, 6, 3, 4]
[1, 2, 5, 6, 4, 3]
[1, 2, 5, 4, 3, 6]
[1, 2, 5, 4, 6, 3]
[1, 2, 4, 3, 6, 5]
[1, 2, 4, 3, 5, 6]
[1, 2, 4, 6, 3, 5]
[1, 2, 4, 6, 5, 3]
[1, 2, 4, 5, 3, 6]
[1, 2, 4, 5, 6, 3]
[1, 3, 2, 6, 5, 4]
[1, 3, 2, 6, 4, 5]
[1, 3, 2, 5, 6, 4]
[1, 3, 2, 5, 4, 6]
[1, 3, 2, 4, 6, 5]
[1, 3, 2, 4, 5, 6]
[1, 3, 6, 2, 5, 4]
[1, 3, 6, 2, 4, 5]
[1, 3, 6, 5, 2, 4]
[1, 3, 6, 5, 4, 2]
[1, 3, 6, 4, 2, 5]
[1, 3, 6, 4, 5, 2]
[1, 3, 5, 2, 6, 4]
[1, 3, 5, 2, 4, 6]
[1, 3, 5, 6, 2, 4]
[1, 3, 5, 6, 4, 2]
[1, 3, 5, 4, 2, 6]
[1, 3, 5, 4, 6, 2]
[1, 3, 4, 2, 6, 5]
[1, 3, 4, 2, 5, 6]
[1, 3, 4, 6, 2, 5]
[1, 3, 4, 6, 5, 2]
[1, 3, 4, 5, 2, 6]
[1, 3, 4, 5, 6, 2]
[1, 6, 2, 3, 5, 4]
[1, 6, 2, 3, 4, 5]
[1, 6, 2, 5, 3, 4]
[1, 6, 2, 5, 4, 3]
[1, 6,

# 79	Find the longest common subsequence between two strings.


In [181]:
'''can be imporved by removing only unique character in string'''
x=3
y=2
s1='ABC'
s2='AC'
#print(x,y,s1,s2)
import numpy as np
mm=[[0 for k in range(y+1)] for l in range(x+1)] #mm=np.zeros([x+1,y+1])
mm
for i in range(1,len(mm)):
    for j in range(1,len(mm[0])):
        #mm[i][j]=1
        #pass
        #print(i,j,'ij')
        if s1[i-1]==s2[j-1]:
            mm[i][j]=1+mm[i-1][j-1]
        else:
            mm[i][j]=max(mm[i-1][j],mm[i][j-1])
        
print(mm)      
mm[i][j]
        

1 1 ij
1 2 ij
2 1 ij
2 2 ij
3 1 ij
3 2 ij
[[0, 0, 0], [0, 1, 1], [0, 1, 1], [0, 1, 2]]


2